### ISSUE TITLE
logprep crashes if startet with empty but set loglevel

### ISSUE THREAD

**Issue by ekneg54** [fkie-cad/Logprep#340]
if the log_level is set in configuration with an empty string `""`, logprep raises following exception

```
'NoneType' object has no attribute 'upper'
Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/logprep/run_logprep.py", line 141, in _setup_logger
    AggregatingLogger.setup(config, logger_disabled=args.disable_logging)
  File "/opt/venv/lib/python3.11/site-packages/logprep/util/aggregating_logger.py", line 56, in setup
    cls.log_level = name_to_level.get(cls.level_str.upper(), INFO)
                                      ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'upper'
```

Solution:

config verification should ensure, the the log_level is set to a valid value

**Comment by ekneg54** [comment]
verified -> done
