### ISSUE TITLE
Dissector: add support for copying/moving a log message field value to another field

### ISSUE THREAD

**Issue by pmc-ph** [fkie-cad/Logprep#380]
**Is your feature request related to a problem? Please describe.**

At the moment it's not possible to copy/move the value of a log field to another field with a given name, using the Dissector Processor.

```
from logprep.processor.dissector.processor import Dissector
rule_dict = {"filter": "message", "description": "", "dissector": {"mapping": {"message": "%{test}"}}}
Dissector.rule_class._create_from_dict(rule_dict)
```

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/workspaces/fda-backend/.venv/lib/python3.10/site-packages/logprep/processor/base/rule.py", line 293, in _create_from_dict
    config = cls.Config(**config)
  File "<attrs generated init logprep.processor.dissector.rule.DissectorRule.Config>", line 37, in __init__
    __attr_validator_mapping(self, __attr_mapping, self.mapping)
  File "/workspaces/fda-backend/.venv/lib/python3.10/site-packages/attr/_make.py", line 2905, in __call__
    v(inst, attr, value)
  File "/workspaces/fda-backend/.venv/lib/python3.10/site-packages/attr/validators.py", line 439, in __call__
    self.value_validator(inst, attr, value[key])
  File "/workspaces/fda-backend/.venv/lib/python3.10/site-packages/attr/validators.py", line 150, in __call__
    raise ValueError(
ValueError: ("'mapping' must match regex '^(([^%]+))?(%\\\\{((\\\\+\\\\([^%]+\\\\))|(\\\\+(?!\\\\([^%]))|([&\\\\?]))?[^\\\\}\\\\%\\\\{\\\\}\\\\+\\\\/\\\\|]*((\\\\/\\\\d*)|(\\\\|(int|float|str|bool)))?\\\\}([^%]+))+(%\\\\{((\\\\+\\\\([^%]+\\\\))|(\\\\+(?!\\\\([^%]))|([&\\\\?]))?[^\\\\}\\\\%\\\\{\\\\}\\\\+\\\\/\\\\|]*((\\\\/\\\\d*)|(\\\\|(int|float|str|bool)))?\\\\})?$' ('%{test}' doesn't)", Attribute(name='mapping', default=Factory(factory=<class 'dict'>, takes_self=False), validator=_AndValidator(_validators=(<instance_of validator for type <class 'dict'>>, <deep_mapping validator for objects mapping <instance_of validator for type <class 'str'>> to <matches_re validator for pattern re.compile('^(([^%]+))?(%\\{((\\+\\([^%]+\\))|(\\+(?!\\([^%]))|([&\\?]))?[^\\}\\%\\{\\}\\+\\/\\|]*((\\/\\d*)|(\\|(int|float|str|bool)))?\\}([^%]+))+(%\\{((\\+\\([^%]+\\))|(\\+(?!\\([^%]))|([&\\?]))?[^\\}\\%\\{\\)>>)), repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=<class 'dict'>, converter=None, kw_only=True, inherited=False, on_setattr=None, alias='mapping'), re.compile('^(([^%]+))?(%\\{((\\+\\([^%]+\\))|(\\+(?!\\([^%]))|([&\\?]))?[^\\}\\%\\{\\}\\+\\/\\|]*((\\/\\d*)|(\\|(int|float|str|bool)))?\\}([^%]+))+(%\\{((\\+\\([^%]+\\))|(\\+(?!\\([^%]))|([&\\?]))?[^\\}\\%\\{\\), '%{test}')
```

**Describe the solution you'd like**

I would like the Dissector to support moving or copying the whole value of a log message field to a given field. This behaviour is supported Elastics' Dissect Processor. 

Considering a log like `{"message": "foo"}` and the following Dissector Config: \
`{"filter": "message", "description": "", "dissector": {"mapping": {"message": "%{test}"}}}`.

I would expect the output to be `{"message": "foo", "test": "foo"}`

**Describe alternatives you've considered**

I'm aware of the fact that the FieldManager Processor can be used for this Use Case. 

**Additional context**

It seems to work with Elastic Beats.

https://dissect-tester.jorgelbg.me/

<img width="1274" alt="dissect-tester" src="https://user-images.githubusercontent.com/132654480/236438438-5dd841ed-cffa-42d7-a03b-a4c386e53568.png">

</p>
</details>

**Comment by ekneg54** [comment]
For this usecase we have the field_manager.
We shouldn't double this feature.
